### ISSUE TITLE
Windows controll buttons are not working

### ISSUE THREAD

**Issue by flobuc** [ekvedaras/redis-gui#53]
Version 2.0 Windows

The windows controls (Minimize, Maximize, Close) are not working.

**Comment by flobuc** [comment]
Sorry, but this is really annoying. Still using 1.2.12 because of that.

**Comment by ekvedaras** [comment]
Sorry, I have pretty much 0 time these days due to reasons. Might last for a couple of months... I would appreciate it if you (or someone else) could try to solve it. Otherwise, gonna have to wait a bit.

As a hint [this is where the custom title bar is supposed to send window control events to the main process](https://github.com/ekvedaras/redis-gui/blob/main/packages/preload/src/titlebar.ts#L16-L20).
There is either some issue in the main process with window controls for Windows (maybe need to manually add listeners to do `mainWindow.minimize()` etc. 🤷 ), although it works on OSX. Or, for some reason, the customer title bar plugin does not properly trigger those events on Windows.

If there are some questions re implementation I'll try to answer them.
